site_name: VS LTK Docs
site_url: https://docs.ltk.wahwah.tk
copyright: Copyright &copy; 2017-2024, ViperousSoft. All Rights Reserved.
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
nav:
  - index.md
  - Ruleset:
    - ruleset/index.md
    - ruleset/a.md
markdown_extensions:
  - toc:
      permalink: true
