site_name: VS LTK Docs
site_url: https://docs.ltk.wahwah.tk
copyright: Copyright © 2017-2024, ViperousSoft. All Rights Reserved.
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
nav:
  - Home: index.md
  - Ruleset:
    - ruleset/index.md
    - A: ruleset/a.md
